"use client"

/**
 * /terms — Terms of Service
 *
 * Substantive stub. Real structure, real content.
 * Needs attorney review before launch.
 * Written in plain language consistent with [us] philosophy.
 */

import { usePathname } from "next/navigation"
import Sidebar from "@/components/sidebar/Sidebar"

const LAST_UPDATED = "March 2026"
const EFFECTIVE_DATE = "March 2026"

const SECTIONS = [
  {
    title: "1. who we are",
    content: `[us] is a product of One Plus LLC, a wholly-owned subsidiary of OMARO PBC (Public Benefit Corporation). Our registered address and contact information is available at omaro-pbc.org.

By using [us], you are entering into an agreement with One Plus LLC. References to "we," "us," or "our" in these terms refer to One Plus LLC and OMARO PBC.`,
  },
  {
    title: "2. what [us] is",
    content: `[us] is a human connection platform that uses AI to help people understand themselves and find meaningful connections with others. The platform includes an intake conversation, a portrait system, a match engine, a journal, and coaching features.

[u] is the AI presence within [us]. [u] is not a therapist, counselor, or mental health professional. [u] is not a substitute for professional mental health support. If you are experiencing a mental health crisis, please contact a qualified professional or crisis line.`,
  },
  {
    title: "3. eligibility",
    content: `You must be at least 18 years old to use [us]. By using the platform, you confirm that you are 18 or older.

[us] is currently available in English only. We make no representations about availability or legality in jurisdictions outside the United States.`,
  },
  {
    title: "4. your account",
    content: `[us] uses anonymous account numbers — no email address or real name is required to create an account. Your account is identified by a unique identifier stored locally on your device.

You are responsible for maintaining access to your account. Because we do not store your email or personal identifying information, we cannot recover a lost account. If you lose access to your device and have not exported your data, your account and data cannot be recovered.

You may delete your account at any time from [profile] → [delete account]. Deletion is permanent and immediate.`,
  },
  {
    title: "5. acceptable use",
    content: `You agree not to use [us] to:

— Impersonate another person or misrepresent your identity
— Harass, abuse, or harm other users
— Attempt to reverse engineer, scrape, or extract data from the platform
— Use the platform for any unlawful purpose
— Attempt to circumvent or disable any security feature
— Use automated tools to interact with the platform

We reserve the right to terminate access for users who violate these terms.`,
  },
  {
    title: "6. AI and [u]",
    content: `[u] is powered by large language models including Claude (Anthropic). AI responses are generated and may contain errors, inaccuracies, or inappropriate content.

[u] is designed to be a supportive presence, not a decision-making authority. Do not rely on [u] for medical, legal, financial, or mental health decisions.

We continuously work to improve [u]'s responses, but we cannot guarantee that all responses will be accurate, appropriate, or free from bias.`,
  },
  {
    title: "7. your content",
    content: `Content you create within [us] — including journal entries, conversation responses, and portrait corrections — belongs to you.

By using [us], you grant One Plus LLC a limited license to process and store your content for the purpose of operating the platform, improving the match engine (in anonymized, aggregated form only, and only with your consent), and providing you with the service.

You can export all your content at any time from [profile] → [export]. You can delete all your content by deleting your account.`,
  },
  {
    title: "8. matching and connections",
    content: `[us] uses a multi-layer algorithm to suggest connections between users. We do not guarantee the accuracy, quality, or safety of any match or connection.

You are responsible for your own safety when meeting or communicating with other users. We strongly recommend exercising caution when meeting people you have connected with online.

[us] is not responsible for the conduct of users outside the platform.`,
  },
  {
    title: "9. NFTs and digital assets",
    content: `[us] offers the option to mint your portrait as an NFT on the Solana blockchain. NFT minting is optional and subject to a fee.

Minted NFTs are stored on a public blockchain. Once minted, an NFT cannot be deleted or altered. The portrait image and text associated with a minted NFT will remain on the blockchain permanently.

We make no representations about the financial value of minted NFTs. NFTs are not investments.

Custodial wallets generated by [us] are provided as a convenience. You are responsible for exporting and securing your private keys. We are not responsible for loss of access to custodial wallets.`,
  },
  {
    title: "10. paid features",
    content: `[us] offers a free tier and a paid tier. Paid features are described at the time of purchase and may change over time.

We use Stripe for payment processing. We do not store your payment information.

Refunds are available within 7 days of purchase if you have not meaningfully used the paid features. Contact legal@omaro-pbc.org for refund requests.

Holding an NFT from the [us] portrait collection may unlock paid features. This benefit may change over time and is not guaranteed indefinitely.`,
  },
  {
    title: "11. intellectual property",
    content: `The [us] platform, including its design, code, frameworks, and content (excluding your personal data and journal entries), is owned by One Plus LLC and protected by applicable intellectual property laws.

The [us] name, logo, and brand are trademarks of OMARO PBC.

The portrait artwork library is licensed exclusively to One Plus LLC. You may not reproduce, distribute, or create derivative works from portrait images without written permission.`,
  },
  {
    title: "12. disclaimers",
    content: `[US] IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

WE DO NOT WARRANT THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE FROM HARMFUL COMPONENTS.`,
  },
  {
    title: "13. limitation of liability",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, ONE PLUS LLC AND OMARO PBC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF [US].

OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING FROM THESE TERMS OR YOUR USE OF THE PLATFORM SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE MONTHS PRECEDING THE CLAIM, OR $100, WHICHEVER IS GREATER.`,
  },
  {
    title: "14. changes to these terms",
    content: `We may update these terms from time to time. We will notify you of material changes by posting a notice within the platform. Your continued use of [us] after the effective date of updated terms constitutes your acceptance.

If you do not agree to updated terms, you may delete your account before the effective date.`,
  },
  {
    title: "15. governing law",
    content: `These terms are governed by the laws of the State of Delaware, without regard to conflict of law principles.

Any disputes arising from these terms shall be resolved through binding arbitration under the rules of the American Arbitration Association, except that either party may seek injunctive relief in a court of competent jurisdiction.`,
  },
  {
    title: "16. contact",
    content: `For questions about these terms, contact us at legal@omaro-pbc.org.

One Plus LLC / OMARO PBC
Sovereign by design.`,
  },
]

export default function TermsPage({ embedded }: { embedded?: boolean } = {}) {
  const pathname = usePathname()

  return (
    <div style={{ display: "flex", minHeight: embedded ? undefined : "100dvh", background: "var(--bg)" }}>
      {!embedded && <Sidebar />}
      <main style={{
        marginLeft: embedded ? 0 : "var(--sidebar-width)",
        flex: 1,
        display: "flex",
        flexDirection: "column",
        minHeight: embedded ? undefined : "100dvh",
        width: embedded ? "100%" : "calc(100vw - var(--sidebar-width))",
      }}>
        <div style={{
          flex: 1,
          overflowY: "auto",
          padding: "48px 40px 80px",
          maxWidth: "860px",
          width: "100%",
          margin: "0 auto",
        }}>

          {/* Header */}
          <div style={{ marginBottom: "48px" }}>
            <div style={{
              fontSize: "10px",
              fontFamily: "var(--font-mono)",
              color: "var(--amber)",
              letterSpacing: "0.1em",
              marginBottom: "12px",
              opacity: 0.8,
            }}>
              [terms of service]
            </div>
            <h1 style={{
              fontSize: "28px",
              fontFamily: "var(--font-sans)",
              color: "var(--text)",
              fontWeight: 300,
              letterSpacing: "-0.5px",
              margin: 0,
              marginBottom: "12px",
            }}>
              terms of service
            </h1>
            <div style={{
              fontSize: "13px",
              fontFamily: "var(--font-mono)",
              color: "var(--dim)",
              fontWeight: 300,
            }}>
              last updated: {LAST_UPDATED} · effective: {EFFECTIVE_DATE}
            </div>
            <div style={{
              marginTop: "20px",
              padding: "16px",
              borderRadius: "10px",
              background: "var(--bg2)",
              border: "1px solid var(--border)",
              fontSize: "13px",
              fontFamily: "var(--font-mono)",
              color: "var(--muted)",
              fontWeight: 300,
              lineHeight: 1.7,
            }}>
              these terms govern your use of [us]. please read them. by using [us], you agree to be bound by these terms.
            </div>
          </div>

          {/* Sections */}
          <div style={{ display: "flex", flexDirection: "column", gap: "36px" }}>
            {SECTIONS.map((section) => (
              <section key={section.title}>
                <div style={{
                  fontSize: "13px",
                  fontFamily: "var(--font-mono)",
                  color: "var(--amber)",
                  letterSpacing: "0.05em",
                  marginBottom: "12px",
                  opacity: 0.9,
                }}>
                  {section.title}
                </div>
                <div style={{
                  fontSize: "14px",
                  fontFamily: "var(--font-mono)",
                  color: "var(--text)",
                  fontWeight: 300,
                  lineHeight: 1.8,
                  whiteSpace: "pre-line",
                }}>
                  {section.content}
                </div>
              </section>
            ))}
          </div>

          {/* Footer */}
          <div style={{
            marginTop: "60px",
            paddingTop: "24px",
            borderTop: "1px solid var(--border)",
            fontSize: "11px",
            fontFamily: "var(--font-mono)",
            color: "var(--dim)",
            lineHeight: 1.7,
          }}>
            [us] | ONE PLUS LLC | Governed by OMARO Public Benefit Corporation.
          </div>

        </div>
      </main>
    </div>
  )
}
